name: Sanitize-linux-build
on: 
  push:
    paths:
    - "linux"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Download and compile linux"
      run: |
        id=$(git rev-parse HEAD:linux)
        cd ..
        wget "https://github.com/skruven96/linux/archive/$id.zip"
        unzip "./$id.zip"
        cd scripts
        ./install-deps.sh
        ./build-linux.sh ../linux-$id tinyconfig    
