name: Sanitize-linux-build
on: push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name:  "Check sub module update"
      run: |
        oldid=$(git rev-parse ${{ github.event.before }}:linux)
        newid=$(git rev-parse ${{ github.event.after }}:linux)
        echo "newid=$newid" >> $GITHUB_ENV
        echo "oldid=$oldid" >> $GITHUB_ENV
    - name: "Download and compile linux"
      if: ${{ env.oldid != env.newid }}
      run: |
        cd ..
        wget "https://github.com/skruven96/linux/archive/${{ env.newid }}.zip"
        unzip "./${{ env.newid }}.zip" -d linux
        cd scripts
        ./build-linux.sh ../linux tinyconfig    
